#! /bin/sh

echo "Heyo! This will use HomeBrew to set up a bunch of apps."
echo ""

read -p 'Continue? (y + Enter to continue, or anything else + Enter to stop):' toContinue

if [[ $toContinue != "Y" && $toContinue != "y" ]]; then
    echo "No problem, I'll be here when you need me."
    echo "Done!"
    exit 0
fi

if which brew > /dev/null
then
    echo "brew is installed, skipping..."
else
    echo "Uh oh, brew itself is not installed. I need to install it to continue."
    echo ""
    read -p 'Install it? (y + Enter to continue, or anything else + Enter to stop):' toContinue

    if [[ $toContinue != "Y" && $toContinue != "y" ]]; then
        echo "No problem, I'll be here when you need me."
        echo "Done!"
        exit 0
    fi

    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew list node || brew install node

brew cask list dotnet-sdk || brew cask install dotnet-sdk
brew cask list signal || brew cask install signal
brew cask list visual-studio-code || brew cask install visual-studio-code
brew cask list slack || brew cask install slack
brew cask list whatsapp || brew cask install whatsapp
brew cask list google-chrome || brew cask install google-chrome
brew cask list spotify || brew cask install spotify
brew cask list 1password || brew cask install 1password
brew cask list github-desktop || brew cask install github-desktop
brew cask list OneDrive || brew cask install OneDrive

brew cleanup --force
rm -f -r /Library/Caches/Homebrew/*